<a href="https://colab.research.google.com/github/PratyushPriyamKuanr271776508/pwskills_numpy/blob/main/Assignment_Numpy_Pratyush_Kuanr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 1. **Purpose and Advantages of NumPy in Scientific Computing and Data Analysis**
NumPy is essential in Python for scientific computing due to its efficiency in handling large datasets and complex mathematical operations. It provides fast array operations, tools for linear algebra, Fourier transforms, and random number generation. Its efficiency comes from the underlying C and Fortran libraries, which allow for operations that are vectorized, meaning they can be applied over entire arrays without needing loops, enhancing speed significantly.

*Advantages:*
- **Efficient Storage and Performance**: Operates faster than Python lists because data is stored in contiguous memory blocks.
- **Vectorization and Broadcasting**: Allows batch operations over arrays without explicit loops.
- **Built-in Functions**: Offers a wide range of mathematical functions for element-wise operations.
- **Interoperability**: Easily integrates with other libraries (e.g., Pandas, Scipy, TensorFlow), enhancing Python's capabilities.

### 2. **Comparison of `np.mean()` and `np.average()`**
- **`np.mean()`** calculates the arithmetic mean along the specified axis without any weighting.
- **`np.average()`** calculates a weighted average if weights are specified; otherwise, it behaves like `np.mean()`.



**Use Case**: Use `np.average()` when weighting is required; otherwise, `np.mean()` is sufficient.


In [2]:
arr = np.array([1, 2, 3, 4])

# Mean
mean_value = np.mean(arr)
print("Mean:", mean_value)

# Weighted Average
weights = np.array([1, 2, 1, 2])
weighted_avg = np.average(arr, weights=weights)
print("Weighted Average:", weighted_avg)

Mean: 2.5
Weighted Average: 2.6666666666666665


### 3. **Reversing a NumPy Array Along Different Axes**

In [4]:
# For a 1D array

arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]
print("Reversed 1D Array:", reversed_1d)

Reversed 1D Array: [4 3 2 1]


In [3]:
# For a 2D array

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Reverse rows
reversed_rows = arr_2d[::-1]
print("Reversed Rows:\n", reversed_rows)

# Reverse columns
reversed_cols = arr_2d[:, ::-1]
print("Reversed Columns:\n", reversed_cols)

Reversed Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed Columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


### 4. **Determining the Data Type of Elements in a NumPy Array**

**Importance**: Proper data types optimize memory usage and performance. For example, using `int32` instead of `float64` can reduce memory consumption.

In [5]:
arr = np.array([1, 2, 3], dtype=np.float64)
print("Data Type:", arr.dtype)

Data Type: float64


### 5. **Defining `ndarrays` in NumPy and Their Key Features**

An `ndarray` (n-dimensional array) in NumPy is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Unlike lists, `ndarrays` support efficient operations, require less memory, and allow element-wise operations.

*Features:*
- **Homogeneous Data**: All elements are of the same type.
- **Efficient Indexing**: Faster access and operations.
- **Vectorized Operations**: Apply operations across arrays without loops.

In [6]:
ndarray = np.array([[1, 2, 3], [4, 5, 6]])
print("NDArray:\n", ndarray)

NDArray:
 [[1 2 3]
 [4 5 6]]


### 6. **Performance Benefits of NumPy Arrays over Python Lists**

NumPy arrays are more memory-efficient and faster due to contiguous memory storage and vectorized operations. When performing large-scale computations, this results in a significant performance boost.

### 7. **Comparison of `vstack()` and `hstack()` Functions**

- **`vstack()`** stacks arrays vertically (row-wise).
- **`hstack()`** stacks arrays horizontally (column-wise).

**Example:**


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stack
vstacked = np.vstack((arr1, arr2))
print("Vertical Stack:\n", vstacked)

# Horizontal stack
hstacked = np.hstack((arr1, arr2))
print("Horizontal Stack:", hstacked)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]


### 8. **Differences between `fliplr()` and `flipud()`**

- **`fliplr()`** flips an array horizontally (left-to-right).
- **`flipud()`** flips an array vertically (top-to-bottom).

**Example:**

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flip Left-Right
flipped_lr = np.fliplr(arr)
print("Flipped Left-Right:\n", flipped_lr)

# Flip Up-Down
flipped_ud = np.flipud(arr)
print("Flipped Up-Down:\n", flipped_ud)

Flipped Left-Right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped Up-Down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


### 9. **Functionality of `array_split()`**

The `array_split()` method splits an array into sub-arrays, allowing uneven splits if the array cannot be divided equally.

**Example:**

In [9]:
arr = np.array([1, 2, 3, 4, 5])
split_arr = np.array_split(arr, 3)
print("Split Array:", split_arr)

Split Array: [array([1, 2]), array([3, 4]), array([5])]


### 10. **Vectorization and Broadcasting**

- **Vectorization** allows operations on entire arrays without looping, which speeds up calculations.
- **Broadcasting** enables operations on arrays of different shapes by virtually expanding smaller arrays to match larger arrays.


**Benefits**: Vectorization and broadcasting make NumPy operations fast and efficient by avoiding Python loops, reducing computation time and memory overhead.

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1])
result = arr1 + arr2  # Broadcasting
print("Broadcasting Result:", result)

arr = np.array([1, 2, 3, 4, 5])
squared_arr = arr ** 2
print("Squared Array (using vectorization):", squared_arr)


Broadcasting Result: [2 3 4]
Squared Array (using vectorization): [ 1  4  9 16 25]


### ***PRACTICAL EXAMPLES***

**1. Create a 3x3 NumPy array with random integers between 1 and 100 and interchange its rows and columns**

In [14]:
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("Transposed Array:\n", transposed_arr)

Original Array:
 [[12 51 25]
 [17 94 35]
 [17 84 33]]
Transposed Array:
 [[12 17 17]
 [51 94 84]
 [25 35 33]]


**2. Generate a 1D NumPy array with 10 elements, reshape it into a 2x5 array, then into a 5x2 array**

In [15]:
arr_1d = np.arange(10)
print("1D Array:\n", arr_1d)

# Reshape into 2x5
arr_2x5 = arr_1d.reshape(2, 5)
print("Reshaped to 2x5:\n", arr_2x5)

# Reshape into 5x2
arr_5x2 = arr_2x5.reshape(5, 2)
print("Reshaped to 5x2:\n", arr_5x2)

1D Array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values, add a border of zeros around it to make a 6x6 array**

In [16]:
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr_4x4)

# Add border of zeros
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Border:\n", arr_6x6)

Original 4x4 Array:
 [[0.20975665 0.42652807 0.17835322 0.75749295]
 [0.36129476 0.41104705 0.90785131 0.57559181]
 [0.46507597 0.7585598  0.7541966  0.40099669]
 [0.99587053 0.3450224  0.75807697 0.56591811]]
6x6 Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.20975665 0.42652807 0.17835322 0.75749295 0.        ]
 [0.         0.36129476 0.41104705 0.90785131 0.57559181 0.        ]
 [0.         0.46507597 0.7585598  0.7541966  0.40099669 0.        ]
 [0.         0.99587053 0.3450224  0.75807697 0.56591811 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Create an array of integers from 10 to 60 with a step of 5**

In [17]:
arr_step = np.arange(10, 61, 5)
print("Array from 10 to 60 with step of 5:\n", arr_step)


Array from 10 to 60 with step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


**5. Create an array of strings ['python', 'numpy', 'pandas'] and apply different case transformations**

In [18]:
arr_str = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_arr = np.char.upper(arr_str)
print("Uppercase:", uppercase_arr)

# Lowercase
lowercase_arr = np.char.lower(arr_str)
print("Lowercase:", lowercase_arr)

# Title case
titlecase_arr = np.char.title(arr_str)
print("Title case:", titlecase_arr)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


**6. Generate an array of words and insert a space between each character of every word**

In [19]:
words = np.array(['data', 'science', 'numpy'])
spaced_words = np.char.join(' ', words)
print("Words with spaces:\n", spaced_words)

Words with spaces:
 ['d a t a' 's c i e n c e' 'n u m p y']


**7. Create two 2D arrays and perform element-wise addition, subtraction, multiplication, and division**

In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Addition
add_result = arr1 + arr2
print("Addition:\n", add_result)

# Subtraction
sub_result = arr1 - arr2
print("Subtraction:\n", sub_result)

# Multiplication
mul_result = arr1 * arr2
print("Multiplication:\n", mul_result)

# Division
div_result = arr1 / arr2
print("Division:\n", div_result)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


**8. Create a 5x5 identity matrix and extract its diagonal elements**

In [21]:
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


**9. Generate an array of 100 random integers between 0 and 1000 and display all prime numbers in the array**

In [22]:
from sympy import isprime

random_ints = np.random.randint(0, 1000, 100)
primes = [num for num in random_ints if isprime(num)]
print("Random Integers:\n", random_ints)
print("Prime Numbers:\n", primes)

Random Integers:
 [278 418 298   3 382 318 545 802  59 384 313  46 786  36 656 337 178 801
 392 426   7 400 877 292 473 409 774 789 878 659 654 949 857 553  47 195
 104 140 641 948 126 115 697 570 702 139 692  82 662 699 292 944 718 593
 217 564 678 521 608 907 785 582 502 450 955 448 882 281 740 949 724 824
 674 467 138 973 339 328 320 739 325 917 574 620 371 155 445 370 799 668
 587 958 700 229  75 842 237 433 894 366]
Prime Numbers:
 [3, 59, 313, 337, 7, 877, 409, 659, 857, 47, 641, 139, 593, 521, 907, 281, 467, 739, 587, 229, 433]


**10. Create an array representing daily temperatures for a month, calculate weekly averages**

In [24]:
# Generate daily temperatures for a month (30 days)
temperatures = np.random.randint(15, 35, size=30)
print("Daily Temperatures:\n", temperatures)

# Reshape into weeks (4 weeks of 7 days each, with an extra day for the 5th week)
temperatures = np.resize(temperatures, (5, 7))
print("Reshaped Temperatures:\n", temperatures)

# Calculate weekly averages
weekly_averages = np.mean(temperatures, axis=1)
print("Weekly Averages:\n", weekly_averages)

Daily Temperatures:
 [20 15 15 21 30 18 32 22 29 20 16 32 33 15 34 33 17 17 15 32 29 15 33 25
 28 25 31 19 15 15]
Reshaped Temperatures:
 [[20 15 15 21 30 18 32]
 [22 29 20 16 32 33 15]
 [34 33 17 17 15 32 29]
 [15 33 25 28 25 31 19]
 [15 15 20 15 15 21 30]]
Weekly Averages:
 [21.57142857 23.85714286 25.28571429 25.14285714 18.71428571]
